name: deploy to prod

on:
  workflow_dispatch

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - name: Deploy bundle to prod
        run: databricks bundle deploy --target prod
        env:
          ARM_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.DATABRICKS_AZURE_TENANT_ID }}