name: deploy to dev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - name: Deploy bundle to dev
        run: databricks bundle deploy --target dev
        env:
          ARM_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.DATABRICKS_AZURE_TENANT_ID }}